---
# Red Hat pull-secret location.
# Can be overridden via CLI:
#   ansible-playbook site.yml -e sno_pullsecret_path=/tmp/pull-secret.json

sno_pullsecret_path: "{{ playbook_dir }}/../.secrets/pull-secret.json"
